'use strict';
const $=id=>document.getElementById(id);
const S={view:'overview',devices:[],proxies:{},configs:{},settings:{modes:{},nodes:{},defaultMode:'rule'},connections:[],rules:null,page:0,group:'',token:'',running:false,traffic:[],delays:new Map(),testing:new Set(),batch:false};
const views={overview:['概览','layout-dashboard'],devices:['设备','monitor-smartphone'],nodes:['节点','network'],rules:['规则','list-filter'],connections:['连接','activity'],settings:['设置','settings']};
S.view=Object.hasOwn(views,location.hash.slice(1))?location.hash.slice(1):'overview';
$('title').textContent=views[S.view][0];
const modes={rule:'规则分流',global:'全局代理',direct:'全部直连'};
const testTargets={basic:{name:'基础连通',url:'https://www.gstatic.com/generate_204'},youtube:{name:'YouTube',url:'https://www.youtube.com/generate_204'},x:{name:'X（推特）',url:'https://x.com/robots.txt'}};
S.nodeQuery='';S.nodeSort='default';S.batchDone=0;S.batchTotal=0;S.cancelBatch=false;
try{S.delays=new Map(JSON.parse(sessionStorage.getItem('routerpro-tests')||'[]'));}catch(e){}
let socket,toastTimer,confirmResolve,busy=false,chartFrame,chartStart=0,chartFromMax=1024,chartToMax=1024,chartMax=1024;
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function icon(name){const n=el('img');n.src='icons/'+name+'.svg';n.alt='';return n;}
function button(text,fn,cls=''){const b=el('button',cls,text);b.type='button';b.addEventListener('click',async()=>{b.disabled=true;const timer=setTimeout(()=>{b.classList.add('is-busy');b.setAttribute('aria-busy','true');},150);try{await fn();}catch(e){error(e);}finally{clearTimeout(timer);b.disabled=false;b.classList.remove('is-busy');b.removeAttribute('aria-busy');}});return b;}
function tool(name,title,fn){const b=button(undefined,fn,'icon');b.append(icon(name));b.title=title;b.setAttribute('aria-label',title);return b;}
function error(e){$('error').textContent=e.message||String(e);$('error').hidden=false;}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function bytes(n){n=Number(n)||0;const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<4){n/=1024;i++;}return(i?n.toFixed(n<10?1:0):Math.round(n))+' '+u[i];}
function meta(name){return /^(剩余流量|套餐到期)/.test(name);}
function mainGroup(){return Object.values(S.proxies).find(p=>p.all&&p.name.includes('节点选择'));}
function deviceMode(d){if(!d.enabled)return'direct';const mode=S.settings.modes[d.mac];return mode&&mode!=='inherit'?mode:S.settings.defaultMode||'rule';}
async function request(url,options={},milliseconds=12000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),milliseconds);try{return await fetch(url,{...options,signal:controller.signal});}catch(e){if(controller.signal.aborted){const timeout=Error('请求超时，请检查网络连接');timeout.name='TimeoutError';throw timeout;}throw e;}finally{clearTimeout(timer);}}
async function api(path,method='GET',body){const r=await request('http://'+location.hostname+':9090'+path,{method,headers:{Authorization:'Bearer '+S.token,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),credentials:'omit',cache:'no-store'});if(!r.ok)throw Error('代理接口请求失败（'+r.status+'）');return r.status===204?null:r.json();}
async function readDevices(){const r=await request('/cgi-bin/devices',{cache:'no-store'});if(!r.ok)throw Error('设备读取失败（'+r.status+'）');const d=await r.json();S.devices=d.devices;S.token=d.csrf;S.running=d.running;S.system=d.system;const settings=await request('/cgi-bin/manage',{cache:'no-store'});if(!settings.ok)throw Error('管理设置读取失败');S.settings=await settings.json();S.settings.modes=S.settings.modes||{};S.settings.nodes=S.settings.nodes||{};$('service').textContent=d.running?'● 服务运行中':'● 服务已停止';$('service').classList.toggle('on',d.running);}
async function manage(body,onProgress){
 const r=await request('/cgi-bin/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,csrf:S.token})});let data=await r.json();if(!r.ok||data.error)throw Error(data.error||'保存失败');
 if(data.job){const stages={waiting:'等待保存…',validating:'正在校验配置…',saving:'正在保存配置…',reloading:'正在重载代理配置…',updating:'正在更新订阅…',applying:'正在应用设备规则…'};const deadline=Date.now()+180000;let complete=false;while(Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,700));let result;try{result=await request('/cgi-bin/manage?job='+encodeURIComponent(data.job),{cache:'no-store'});}catch(e){continue;}const status=await result.json();if(status.pending){onProgress?.(stages[status.stage]||'正在保存…');continue;}if(!result.ok||status.error)throw Error(status.error||'保存失败');complete=true;break;}if(!complete)throw Error('保存任务仍在处理中，请刷新查看结果');}
 try{await readDevices();await readCore();}catch(e){error(Error('配置已保存，状态刷新失败，请刷新页面'));}
}
async function readCore(){const [p,c,v,providers]=await Promise.all([api('/proxies'),api('/configs'),api('/version'),api('/providers/proxies')]);S.proxies=p.proxies;S.configs=c;S.version=v.version;S.providers=providers.providers||{};for(const provider of Object.values(S.providers))for(const node of provider.proxies||[])if(!S.proxies[node.name])S.proxies[node.name]=node;const groups=Object.values(S.proxies).filter(p=>p.all);if(S.group!=='__all'&&!groups.some(g=>g.name===S.group))S.group=mainGroup()?.name||groups[0]?.name||'';}
async function readConnections(){const d=await api('/connections');S.connections=d.connections||[];S.download=d.downloadTotal;S.upload=d.uploadTotal;const now=Date.now(),previous=S.counterSample;S.counterSample={time:now,down:S.download,up:S.upload};if(S.view==='overview'&&!document.hidden&&now-(S.lastWS||0)>3500){const seconds=previous?(now-previous.time)/1000:1;acceptTraffic({down:previous?Math.max(0,(S.download-previous.down)/seconds):0,up:previous?Math.max(0,(S.upload-previous.up)/seconds):0});}}
function empty(root,text){root.replaceChildren(el('div','empty',text));}
function filterInput(placeholder,oninput,value=''){const input=el('input');input.type='search';input.placeholder=placeholder;input.setAttribute('aria-label',placeholder);input.value=value;input.addEventListener('input',()=>oninput(input.value));return input;}
function select(options,value,onchange,label){const n=el('select');n.setAttribute('aria-label',label);for(const [v,text]of options){const o=el('option','',text);o.value=v;n.append(o);}n.value=value;n.addEventListener('change',()=>onchange(n.value));return n;}
function rowHead(labels){const n=el('div','row head');labels.forEach(t=>n.append(el('span','',t)));return n;}
function confirmAction(title,text){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm').showModal();return new Promise(r=>confirmResolve=r);}
function confirmDone(value){$('confirm').close();confirmResolve?.(value);confirmResolve=null;}
async function setMode(mode){if(mode===S.settings.defaultMode)return;if(!await confirmAction('默认模式切换为'+modes[mode]+'？','将影响选择“跟随默认”的设备。保存会短暂重载代理配置。'))return;await manage({action:'default',mode});render();toast('默认设备模式已更新');}
function renderOverview(root){
 const metrics=el('div','metrics'),sys=S.system,uptime=sys?.uptime||0;
 const items=[['代理设备',S.devices.filter(d=>deviceMode(d)!=='direct').length,'共 '+S.devices.length+' 台设备'],['当前连接',S.connections.length,'Mihomo '+(S.version||'--')],['可用内存',sys?bytes(sys.memoryAvailable*1024):'--','总内存 '+(sys?bytes(sys.memoryTotal*1024):'--')],['路由器运行时间',uptime>=86400?Math.floor(uptime/86400)+' 天':Math.floor(uptime/3600)+' 小时','开机自动启动：'+(S.settings.bootEnabled?'已启用':'未启用')]];
 for(const [label,value,note]of items){const n=el('div','metric');n.append(el('span','',label),el('strong','',value),el('small','',note));metrics.append(n);}root.append(metrics,el('h2','','路由策略'));
 const policy=el('div','policy'),seg=el('div','segmented');for(const [mode,name]of Object.entries(modes)){const b=button(mode==='direct'?'直连':name,()=>setMode(mode),S.settings.defaultMode===mode?'active':'');b.setAttribute('aria-pressed',String(S.settings.defaultMode===mode));seg.append(b);}policy.append(el('span','','默认设备模式'),seg);
 const node=el('div','policy');node.append(el('span','','主节点'),button(mainGroup()?.now||'--',()=>navigate('nodes'),'link'));root.append(policy,node);
 const heading=el('div','chart-heading'),rates=el('div','rates');rates.append(el('span','','↓ '),el('span','','↑ '));rates.children[0].id='rate-down';rates.children[1].id='rate-up';heading.append(el('h2','','实时流量'),rates);
 const canvas=el('canvas');canvas.id='traffic';canvas.height=160;canvas.setAttribute('aria-label','实时上传与下载流量');const totals=el('div','totals');totals.id='totals';totals.append(el('span','','累计下载 '+bytes(S.download)),el('span','','累计上传 '+bytes(S.upload)));root.append(heading,canvas,totals);drawTraffic();
}
function renderDevices(root){
 const toolbar=el('div','toolbar'),list=el('div','devices');toolbar.append(el('span','',S.devices.length+' 台设备 · '+S.devices.filter(d=>deviceMode(d)!=='direct').length+' 台已开启代理'));
 const body=el('div');list.append(rowHead(['设备','网络地址','当前状态','设备模式','操作']),body);
 function draw(q=''){
  body.replaceChildren();for(const d of S.devices.filter(d=>[d.name,d.ip,d.mac].join(' ').toLowerCase().includes(q.toLowerCase()))){
   const row=el('div','row'),name=el('div');name.append(el('div','name',d.name==='*'?'未命名设备':d.name==='Offline device'?'离线设备':d.name));if(d.protected)name.append(el('div','sub','当前电脑'));
   const address=el('div','address');address.append(el('div','',d.ip||'离线'),el('div','sub',d.mac));
   const configured=S.settings.modes[d.mac]||'inherit',effective=deviceMode(d),proxied=effective!=='direct';
   const status=el('div','status');status.append(el('span','badge '+(proxied?(S.running?'on':'pending'):''),proxied?(S.running?(effective==='global'?'全局代理':'规则分流'):'代理未运行'):'直连'));
   const mode=select([['inherit','跟随默认'],['rule','规则分流'],['global','全局代理'],['direct','直连']],d.enabled?configured:'direct',async value=>{
    mode.disabled=true;try{await manage({action:'device',mac:d.mac,mode:value});draw(q);toast('设备模式已保存');}catch(e){mode.value=d.enabled?configured:'direct';error(e);}finally{mode.disabled=d.protected;}
   },d.name+' 设备模式');mode.className='device-mode';mode.disabled=d.protected;mode.title=d.protected?'当前电脑固定直连，使用本机代理':'此设备的独立路由模式';
   const actions=el('div','actions'),b=button(proxied?'关闭代理':'开启代理',async()=>{
    const selected=proxied?'direct':S.settings.defaultMode==='direct'?'rule':configured==='direct'?'inherit':configured;
    await manage({action:'device',mac:d.mac,mode:selected});draw(q);toast(proxied?'已关闭设备代理':'已开启设备代理');
   });b.disabled=d.protected;b.title=d.protected?'当前电脑固定直连，使用本机代理':(proxied?'关闭':'开启')+'此设备的路由器代理';actions.append(b);row.append(name,address,status,mode,actions);body.append(row);
  }if(!body.children.length)empty(body,'没有匹配的设备');
 }
 toolbar.append(filterInput('搜索设备、IP 或 MAC',draw));root.append(toolbar,list);draw();
}
function renderNodeList(root){
 const toolbar=el('div','toolbar node-toolbar'),summary=el('div','summary'),list=el('div','nodes'),body=el('div'),wrap=el('div','node-wrap');
 const groups=Object.values(S.proxies).filter(p=>p.all);toolbar.append(select([['__all','全部节点'],...groups.map(g=>[g.name,g.name])],S.group,v=>{S.group=v;draw();},'策略组'),filterInput('搜索节点',v=>{S.nodeQuery=v;draw();},S.nodeQuery));
 const test=button('测试全部节点',async()=>{if(S.batch)return;S.batch=true;S.cancelBatch=false;S.batchDone=0;const queue=names().filter(name=>!S.proxies[name]?.all&&!['DIRECT','REJECT','COMPATIBLE','PASS'].includes(name));const target=S.batchTarget||'all';S.batchTotal=queue.length;draw();try{await Promise.all(Array.from({length:2},async()=>{while(queue.length&&!S.cancelBatch){await testNode(queue.shift(),target,true);S.batchDone++;draw();}}));toast(S.cancelBatch?'测试已停止':'节点测试完成');}finally{S.batch=false;draw();}},'command');test.prepend(icon('zap'));test.title='测试当前列表中的节点';
 const stop=button('停止测试',()=>{S.cancelBatch=true;stop.disabled=true;});stop.hidden=true;
 const add=button('导入节点',()=>openNodeEditor(), 'primary command');add.prepend(icon('network'));toolbar.append(add,button('批量导入',()=>openBatchImport(),'command'));
 const testing=el('div','toolbar testing-toolbar');testing.append(select([['all','全部平台'],...Object.entries(testTargets).map(([key,t])=>[key,t.name])],S.batchTarget||'all',value=>{S.batchTarget=value;},'批量检测平台'),test,stop);
 const filters=el('div','toolbar node-filters'),count=el('span','muted'),sort=select([['default','默认排序'],['basic','基础响应优先'],['youtube','YouTube 响应优先'],['x','X 响应优先']],S.nodeSort,v=>{S.nodeSort=v;draw();},'节点排序');filters.append(count,sort,el('span','muted','响应耗时 · ms'));
 const head=rowHead(['节点','类型','基础连通','YouTube','X（推特）','操作']);list.append(head,body);wrap.append(list);root.append(summary,toolbar,testing,filters,wrap);enableColumnResize(list,head,'nodes',[150,60,76,76,76,190]);
 function names(){const source=S.group==='__all'?Object.values(S.proxies).filter(p=>!p.all&&!['DIRECT','REJECT','COMPATIBLE','PASS'].includes(p.name)).map(p=>p.name):S.proxies[S.group]?.all||[];const names=source.filter(n=>!meta(n)&&n.toLowerCase().includes(S.nodeQuery.toLowerCase()));const latency=n=>S.delays.get(S.nodeSort+'|'+n)>0?S.delays.get(S.nodeSort+'|'+n):Infinity;names.sort((a,b)=>Number(!!S.settings.pins?.[b])-Number(!!S.settings.pins?.[a])||(S.nodeSort==='default'?0:latency(a)-latency(b)));return names;}
 async function testNode(name,target='all',batch=false){
  if(S.testing.has(name))return;S.testing.add(name);draw();try{for(const key of target==='all'?Object.keys(testTargets):[target]){if(batch&&S.cancelBatch)break;S.activeTest=S.activeTest||new Map();S.activeTest.set(name,key);draw();try{const d=await api('/proxies/'+encodeURIComponent(name)+'/delay?timeout=5000&url='+encodeURIComponent(testTargets[key].url));S.delays.set(key+'|'+name,d.delay||0);}catch(e){S.delays.set(key+'|'+name,0);}try{sessionStorage.setItem('routerpro-tests',JSON.stringify([...S.delays]));}catch(e){}draw();}}finally{S.testing.delete(name);S.activeTest?.delete(name);draw();}
 }
 function draw(){
  const g=S.proxies[S.group],nodes=names();summary.replaceChildren(el('span','muted',S.group==='__all'?'主策略组当前使用':'当前使用'),el('strong','',g?.now||mainGroup()?.now||'--'),el('span','badge',groupType(g?.type||'Selector')));count.textContent=nodes.length+' 个选项';test.disabled=S.batch;test.lastChild.textContent=S.batch?'测试中 '+S.batchDone+'/'+S.batchTotal:'测试全部节点';stop.hidden=!S.batch;stop.disabled=S.cancelBatch;body.replaceChildren();
  for(const name of nodes){const p=S.proxies[name]||{},chosen=g?.now===name,row=el('div','row'+(chosen?' selected':'')),label=el('div','node-identity'),title=el('div','node-title'),pinned=!!S.settings.pins?.[name],source=nodeSource(name)||(S.settings.nodes[name]?'手动导入':p.all?'':'原有配置');if(pinned){const pin=icon('pin');pin.className='pin-mark';pin.title='已置顶';pin.alt='已置顶';title.append(pin);}title.append(el('div','name',name));label.append(title,el('div','sub mobile-type',(p.all?'策略组':p.type||'--')+(source?' · '+source:'')));if(source)label.append(el('div','sub desktop-source',source));row.append(label,el('div','node-type muted',p.all?'策略组':p.type||'--'));
   for(const [key,target]of Object.entries(testTargets)){
    const cell=el('div','platform-cell'),delay=S.delays.get(key+'|'+name),pending=S.activeTest?.get(name)===key;
    const result=button(pending?'测试中':delay>0?delay+' ms':delay===0?'失败':'测试',()=>testNode(name,key),'test-result'+(delay>0?' good':delay===0?' bad':''));result.title='测试 '+name+' 的'+target.name+'响应';result.setAttribute('aria-label',result.title);result.disabled=S.testing.has(name)||['DIRECT','REJECT'].includes(name);if(!pending&&delay===undefined)result.prepend(icon('zap'));cell.append(el('span','platform-label',target.name),result);row.append(cell);
   }
   const actions=el('div','actions'),t=button('测速',()=>testNode(name),'command node-test');t.prepend(icon('zap'));t.title='测试此节点的基础连通、YouTube 和 X';t.setAttribute('aria-label','测试 '+name+' 的全部平台');t.disabled=S.testing.has(name)||['DIRECT','REJECT'].includes(name);
   const b=button(chosen?'使用中':'使用',async()=>{let group=S.group;if(group==='__all'){await chooseNodeGroup(name);return;}await api('/proxies/'+encodeURIComponent(group),'PUT',{name});await readCore();draw();toast('节点选择已保存');},'choose'+(chosen?' primary':''));b.disabled=chosen||(g&&g.type!=='Selector');b.title=g&&g.type!=='Selector'?'由策略组自动选择节点':'';b.setAttribute('aria-label',(chosen?'正在使用 ':'使用 ')+name);actions.append(t,b);
   if(!p.all&&!['DIRECT','REJECT'].includes(name)){
    const menu=el('details','node-menu'),toggle=el('summary','icon');toggle.append(icon('ellipsis'));toggle.title='管理 '+name;toggle.setAttribute('aria-label',toggle.title);const items=el('div','menu-items');
    const pin=button(pinned?'取消置顶':'置顶节点',async()=>{menu.open=false;await manage({action:'pin-node',name,pinned:!pinned});draw();toast(pinned?'已取消置顶':'节点已置顶');},'menu-item command');pin.prepend(icon(pinned?'pin-off':'pin'));items.append(pin);
    if(S.settings.nodes[name]){items.append(button('编辑节点',()=>{menu.open=false;openNodeEditor(name);},'menu-item'));items.append(button('复制分享链接',async()=>{const link=S.settings.nodes[name].uri;try{await navigator.clipboard.writeText(link);toast('分享链接已复制');}catch(e){const d=managerDialog('节点分享链接'),text=el('textarea');text.value=link;text.readOnly=true;d.field('分享链接',text);text.select();}},'menu-item'));}
    if(!nodeSource(name))items.append(button('删除节点',async()=>{menu.open=false;if(await confirmAction('删除此节点？',name+'。保存会短暂重载代理配置；正在使用此节点的策略组将改用可用选项。')){await manage({action:'delete-node',name});draw();toast('节点已删除');}},'menu-item danger'));else items.append(button('管理订阅',()=>{S.nodeTab='subscriptions';render();},'menu-item'));menu.append(toggle,items);menu.addEventListener('toggle',()=>{if(menu.open)document.querySelectorAll('.node-menu[open]').forEach(other=>{if(other!==menu)other.open=false;});});actions.append(menu);
   }
   row.append(actions);body.append(row);
  }if(!nodes.length)empty(body,'没有匹配的节点');
 }draw();
}
function enableColumnResize(list,head,key,minimums){
 const storage='routerpro-columns-'+key;let widths;
 try{const saved=JSON.parse(localStorage.getItem(storage)||'null');if(Array.isArray(saved)&&saved.length===minimums.length&&saved.every((v,i)=>Number.isFinite(v)&&v>=minimums[i]&&v<=1200))widths=saved;}catch(e){}
 const isTable=list.tagName==='TABLE';let columns;
 function apply(){if(!widths)return;if(isTable){if(!columns){columns=el('colgroup');widths.forEach(()=>columns.append(el('col')));list.prepend(columns);}widths.forEach((w,i)=>columns.children[i].style.width=w+'px');list.style.width=widths.reduce((a,b)=>a+b,0)+'px';}else{list.style.setProperty('--columns',widths.map(w=>w+'px').join(' '));list.style.setProperty('--table-width',widths.reduce((a,b)=>a+b,0)+(widths.length-1)*12+'px');}}
 function save(){try{localStorage.setItem(storage,JSON.stringify(widths));}catch(e){}}
 apply();[...head.children].forEach((cell,index)=>{
  const handle=el('span','column-resizer');handle.tabIndex=0;handle.setAttribute('role','separator');handle.setAttribute('aria-orientation','vertical');handle.setAttribute('aria-label','调整'+cell.textContent+'列宽');handle.title='拖动调整列宽，双击恢复默认';
  function measure(){if(!widths)widths=isTable?[...head.children].map(n=>n.getBoundingClientRect().width):getComputedStyle(head).gridTemplateColumns.split(' ').map(parseFloat);}
  handle.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.preventDefault();measure();const start=e.clientX,original=widths[index];handle.setPointerCapture(e.pointerId);document.body.classList.add('resizing');const move=e=>{widths[index]=Math.max(minimums[index],Math.min(1200,original+e.clientX-start));apply();};const end=()=>{handle.removeEventListener('pointermove',move);document.body.classList.remove('resizing');save();};handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',end,{once:true});handle.addEventListener('pointercancel',end,{once:true});});
  handle.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();measure();widths[index]=Math.max(minimums[index],Math.min(1200,widths[index]+(e.key==='ArrowRight'?10:-10)));apply();save();});
  handle.addEventListener('dblclick',()=>{widths=null;list.style.removeProperty('--columns');list.style.removeProperty('--table-width');list.style.removeProperty('width');columns?.remove();columns=null;try{localStorage.removeItem(storage);}catch(e){}});cell.append(handle);
 });
}
function openNodeEditor(original=''){
 const existing=S.settings.nodes[original],dialog=el('dialog','node-editor'),title=el('h2','',original?'编辑节点':'导入节点');
 const uriLabel=el('label','editor-field','分享链接'),uri=el('textarea');uri.rows=5;uri.placeholder='vless://、vmess://、trojan://、ss://、hy2://';uri.setAttribute('aria-label','节点分享链接');uri.value=existing?.uri||'';uri.spellcheck=false;uriLabel.append(uri);
 const nameLabel=el('label','editor-field','节点名称'),name=el('input');name.placeholder='使用链接中的名称';name.setAttribute('aria-label','节点名称');name.value=original;nameLabel.append(name);
 const preview=el('div','node-preview muted'),message=el('div','editor-error');message.setAttribute('role','alert');const note=el('p','muted','保存会短暂重载代理配置。');const actions=el('div','actions');
 const cancel=button('取消',()=>dialog.close()),save=button('保存节点',async()=>{save.disabled=true;uri.disabled=true;name.disabled=true;cancel.disabled=true;try{const data=parseNodeShare(uri.value,name.value);message.textContent='正在校验并保存…';await manage({action:'save-node',...data,original},stage=>message.textContent=stage);dialog.close();render();toast('节点已保存');}catch(e){message.textContent=e.name==='TimeoutError'?'管理请求超时，请刷新确认保存结果':e.message;}finally{uri.disabled=false;name.disabled=false;cancel.disabled=false;}},'primary');actions.append(cancel,save);
 function update(){try{const {node}=parseNodeShare(uri.value,name.value);preview.textContent=node.type.toUpperCase()+' · '+node.server+':'+node.port;save.disabled=false;message.textContent='';}catch(e){preview.textContent='';save.disabled=true;message.textContent=uri.value?e.message:'';}}
 uri.addEventListener('input',update);name.addEventListener('input',update);dialog.append(title,uriLabel,nameLabel,preview,note,message,actions);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal();update();
}
async function readRules(){if(S.rules===null){const d=await api('/rules');S.rules=d.rules.map((r,i)=>({...r,order:i+1}));}}
function renderRules(root){
 let query='',type='',policy='';const toolbar=el('div','toolbar'),wrap=el('div','table-wrap'),table=el('table'),head=el('thead'),hr=el('tr'),body=el('tbody'),pagination=el('div','pagination');for(const t of ['顺序','类型','匹配内容','策略'])hr.append(el('th','',t));head.append(hr);table.append(head,body);wrap.append(table);
 toolbar.append(filterInput('搜索域名、IP 或策略',v=>{query=v;S.page=0;draw();}),select([['','全部类型'],...[...new Set(S.rules.map(r=>r.type))].sort().map(v=>[v,v])],'',v=>{type=v;S.page=0;draw();},'规则类型'),select([['','全部策略'],...[...new Set(S.rules.map(r=>r.proxy))].sort().map(v=>[v,v])],'',v=>{policy=v;S.page=0;draw();},'规则策略'));
 const count=el('span'),page=el('span'),prev=tool('chevron-left','上一页',()=>{S.page--;draw();}),next=tool('chevron-right','下一页',()=>{S.page++;draw();});pagination.append(count,prev,page,next);root.append(toolbar,wrap,pagination);enableColumnResize(table,hr,'rules',[55,110,160,140]);
 function draw(){const rules=S.rules.filter(r=>(!type||r.type===type)&&(!policy||r.proxy===policy)&&[r.payload,r.type,r.proxy].join(' ').toLowerCase().includes(query.toLowerCase())),pages=Math.max(1,Math.ceil(rules.length/50));S.page=Math.max(0,Math.min(S.page,pages-1));body.replaceChildren();for(const r of rules.slice(S.page*50,(S.page+1)*50)){const row=el('tr');for(const v of [r.order,r.type,r.payload||'全部',r.proxy])row.append(el('td','',v));body.append(row);}if(!rules.length){const row=el('tr'),cell=el('td','empty','没有匹配的规则');cell.colSpan=4;row.append(cell);body.append(row);}count.textContent=rules.length+' 条规则';page.textContent=(S.page+1)+' / '+pages;prev.disabled=S.page===0;next.disabled=S.page>=pages-1;}draw();
}
let drawConnections;
function renderConnections(root){
 let query='';S.expandedDevices=S.expandedDevices||new Map();const toolbar=el('div','toolbar'),count=el('span'),list=el('div','device-connection-list'),close=button('关闭全部连接',async()=>{if(await confirmAction('关闭全部代理连接？','正在使用代理的应用会断开并重新连接。')){await api('/connections','DELETE');await readConnections();draw();toast('全部代理连接已关闭');}},'command danger');close.prepend(icon('trash-2'));toolbar.append(count,filterInput('搜索设备、目标或节点',v=>{query=v;draw();}),close);root.append(toolbar,list);
 const device=ip=>{const d=S.devices.find(d=>d.ip===ip);return d?.name&&d.name!=='*'?d.name:ip==='router'?'路由器':ip;};
 function draw(){
  const groups=new Map();for(const c of S.connections){const ip=c.metadata.sourceIP||'router';if(!groups.has(ip))groups.set(ip,[]);groups.get(ip).push(c);}
  count.textContent=groups.size+' 台设备 · '+S.connections.length+' 个连接';close.disabled=!S.connections.length;list.replaceChildren();
  for(const [ip,all]of [...groups].sort((a,b)=>b[1].length-a[1].length)){
   const connections=all.filter(c=>[device(ip),ip,c.metadata.host,c.metadata.destinationIP,...(c.chains||[])].join(' ').toLowerCase().includes(query.toLowerCase()));if(!connections.length)continue;
   const group=el('details','device-connections'),summary=el('summary'),chevron=icon('chevron-right');chevron.className='chevron';const identity=el('div');identity.append(el('div','name',device(ip)),el('div','sub',ip==='router'?'代理核心':ip));
   const amount=el('div','group-traffic');amount.append(el('span','','↓ '+bytes(all.reduce((n,c)=>n+c.download,0))),el('span','','↑ '+bytes(all.reduce((n,c)=>n+c.upload,0))));
   const cut=tool('trash-2','关闭 '+device(ip)+' 的全部连接',async()=>{if(await confirmAction('关闭此设备的全部连接？',device(ip)+' · '+all.length+' 个连接。应用会重新建立连接。')){const queue=[...all];await Promise.all(Array.from({length:3},async()=>{while(queue.length){const c=queue.shift();await api('/connections/'+encodeURIComponent(c.id),'DELETE');}}));await readConnections();draw();toast('此设备的连接已关闭');}});cut.classList.add('danger');cut.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();});summary.append(chevron,identity,el('span','badge',connections.length+' 个连接'),amount,cut);
   const body=el('div','connections');for(const c of connections){
    const m=c.metadata,row=el('div','row'),protocol=el('div','source'),destination=el('div','destination'),bytesCell=el('div','bytes'),seconds=Math.max(0,Math.floor((Date.now()-Date.parse(c.start))/1000));protocol.append(el('div','name',m.network.toUpperCase()),el('div','sub',Number.isFinite(seconds)?seconds>=60?Math.floor(seconds/60)+' 分 '+seconds%60+' 秒':seconds+' 秒':'--'));destination.append(el('div','name',(m.host||m.destinationIP)+':'+m.destinationPort),el('div','sub',(c.chains||[]).slice().reverse().join(' → ')),el('div','sub',c.rule+(c.rulePayload?' · '+c.rulePayload:'')));bytesCell.append(el('div','','↓ '+bytes(c.download)),el('div','','↑ '+bytes(c.upload)));const b=tool('x','关闭 '+(m.host||m.destinationIP)+' 的连接',async()=>{await api('/connections/'+encodeURIComponent(c.id),'DELETE');await readConnections();draw();toast('连接已关闭');});row.append(protocol,destination,bytesCell,b);body.append(row);
   }
   group.append(summary,body);if(!S.expandedDevices.has(ip))S.expandedDevices.set(ip,list.children.length===0);group.open=S.expandedDevices.get(ip);group.addEventListener('toggle',()=>S.expandedDevices.set(ip,group.open));list.append(group);
  }if(!list.children.length)empty(list,'没有匹配的连接');
 }drawConnections=draw;draw();
}
function renderSettings(root){
 const startup=el('section','settings-section startup-section');startup.append(el('h2','','启动设置'));const bootRow=el('div','boot-setting'),bootLabel=el('label','boot-toggle','开机自动启动'),boot=el('input');boot.type='checkbox';boot.checked=!!S.settings.bootEnabled;boot.setAttribute('role','switch');boot.setAttribute('aria-label','开机自动启动');const bootState=el('span','badge'+(boot.checked?' on':''),boot.checked?'已开启':'已关闭');boot.addEventListener('change',async()=>{boot.disabled=true;boot.setAttribute('aria-busy','true');const value=boot.checked;bootState.textContent='保存中…';try{await manage({action:'boot',enabled:value});bootState.textContent=value?'已开启':'已关闭';bootState.classList.toggle('on',value);toast(value?'已开启开机自动启动':'已关闭开机自动启动');}catch(e){boot.checked=!value;bootState.textContent=boot.checked?'已开启':'已关闭';error(e);}finally{boot.disabled=false;boot.removeAttribute('aria-busy');}});bootLabel.append(boot);bootRow.append(bootLabel,bootState);startup.append(bootRow);root.append(startup);
 const account=el('section','settings-section'),form=el('form','account-form');account.append(el('h2','','管理账号'));
 function field(label,type,autocomplete,value=''){const row=el('label','account-field'),caption=el('span','field-caption',label),wrap=el('div','field-control'),input=el('input');input.type=type;input.autocomplete=autocomplete;input.value=value;input.required=true;input.setAttribute('aria-label',label);wrap.append(input);if(type==='password'){const reveal=tool('eye','显示'+label,()=>{input.type=input.type==='password'?'text':'password';const visible=input.type==='text';reveal.replaceChildren(icon(visible?'eye-off':'eye'));reveal.title=(visible?'隐藏':'显示')+label;reveal.setAttribute('aria-label',reveal.title);reveal.setAttribute('aria-pressed',String(visible));});reveal.classList.add('password-reveal');reveal.setAttribute('aria-pressed','false');wrap.classList.add('password-control');wrap.append(reveal);}row.append(caption,wrap);form.append(row);return input;}
 const username=field('用户名','text','username',S.settings.adminUser||'rd15');username.maxLength=32;username.pattern='[A-Za-z0-9_.-]+';
 const current=field('当前密码','password','current-password'),password=field('新密码','password','new-password'),repeat=field('确认新密码','password','new-password');password.minLength=10;password.maxLength=128;password.placeholder='至少 10 位';
 const message=el('div','form-error');message.setAttribute('role','alert');const save=el('button','primary command','保存账号');save.type='submit';save.prepend(icon('check'));const controls=el('div','account-actions'),reset=button('取消修改',()=>{username.value=S.settings.adminUser||'rd15';for(const input of [current,password,repeat]){input.value='';input.removeAttribute('aria-invalid');input.type='password';}form.querySelectorAll('.password-reveal').forEach(b=>{b.replaceChildren(icon('eye'));b.setAttribute('aria-pressed','false');const label=b.closest('label').querySelector('.field-caption').textContent;b.title='显示'+label;b.setAttribute('aria-label',b.title);});message.textContent='';});controls.append(save,reset);form.append(el('div','password-hint muted','新密码长度：10–128 位'),message,controls);
 form.addEventListener('submit',async e=>{e.preventDefault();message.textContent='';for(const input of [username,current,password,repeat])input.removeAttribute('aria-invalid');if(password.value!==repeat.value){message.textContent='两次新密码不一致';repeat.setAttribute('aria-invalid','true');repeat.focus();return;}save.disabled=true;reset.disabled=true;save.classList.add('is-busy');save.setAttribute('aria-busy','true');save.lastChild.textContent='正在保存…';try{
  const r=await request('/cgi-bin/manage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'credentials',csrf:S.token,username:username.value,currentPassword:current.value,password:password.value})});const data=await r.json();if(!r.ok||data.error)throw Error(data.error==='Current password is incorrect'?'当前密码不正确':data.error||'保存失败');
  form.replaceChildren(el('p','','管理账号已更新，请使用新账号密码重新登录。'));toast('账号已保存');setTimeout(()=>location.reload(),5000);
 }catch(e){message.textContent=e.message;if(e.message==='当前密码不正确'){current.setAttribute('aria-invalid','true');current.focus();}save.disabled=false;reset.disabled=false;save.classList.remove('is-busy');save.removeAttribute('aria-busy');save.lastChild.textContent='保存账号';}});account.append(form);root.append(account);
 const info=el('section','settings-section'),details=el('dl','settings-info');info.append(el('h2','','服务信息'));
 for(const [label,value]of [['管理地址','http://'+location.hostname+':9091/'],['代理地址',location.hostname+':7890'],['代理用户名',S.settings.proxyUser||'rd15'],['核心版本','Mihomo '+S.version],['设备型号','Xiaomi BE3600（RD15）']]){details.append(el('dt','',label),el('dd','',value));}info.append(details);root.append(info);
}
function render(){const root=$('content'),view=S.view==='nodes'?S.view+':'+S.nodeTab:S.view,changed=root.dataset.view!==view;root.replaceChildren();if(S.view==='overview')renderOverview(root);else if(S.view==='devices')renderDevices(root);else if(S.view==='nodes')renderNodes(root);else if(S.view==='rules')renderRules(root);else if(S.view==='settings')renderSettings(root);else renderConnections(root);root.dataset.view=S.view==='nodes'?S.view+':'+S.nodeTab:S.view;if(changed&&!matchMedia('(prefers-reduced-motion: reduce)').matches)root.animate([{opacity:.35,transform:'translateY(4px)'},{opacity:1,transform:'translateY(0)'}],{duration:170,easing:'ease-out'});manageTraffic();}
async function navigate(view){if(!Object.hasOwn(views,view))view='overview';const changed=S.view!==view;S.view=view;if(location.hash!=='#'+view)history.pushState(null,'','#'+view);if(changed)window.scrollTo(0,0);$('title').textContent=views[view][0];document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-current',b.dataset.view===view?'page':'false');});$('error').hidden=true;try{if(view==='rules'){empty($('content'),'加载中');await readRules();}else if(view==='connections')await readConnections();else if(view==='nodes')await readCore();else if(view==='devices'||view==='settings')await readDevices();if(S.view===view)render();}catch(e){error(e);}manageTraffic();}
document.addEventListener('click',e=>{document.querySelectorAll('.node-menu[open]').forEach(menu=>{if(!menu.contains(e.target))menu.open=false;});});
async function refresh(){if(busy)return;busy=true;$('refresh').disabled=true;$('refresh').classList.add('is-busy');$('refresh').setAttribute('aria-busy','true');$('error').hidden=true;try{await readDevices();if(S.running){await readCore();await readConnections();if(S.view==='rules'){S.rules=null;await readRules();}}if(S.view==='rules'&&!S.rules)empty($('content'),'代理服务未运行');else render();}finally{busy=false;$('refresh').disabled=false;$('refresh').classList.remove('is-busy');$('refresh').removeAttribute('aria-busy');}}
function manageTraffic(){const active=S.view==='overview'&&!document.hidden&&S.running&&S.token;if(!active){socket?.close();socket=null;cancelAnimationFrame(chartFrame);return;}if(socket)return;try{const ws=new WebSocket('ws://'+location.hostname+':9090/traffic?token='+encodeURIComponent(S.token));socket=ws;ws.onmessage=e=>{S.lastWS=Date.now();acceptTraffic(JSON.parse(e.data));};ws.onclose=()=>{if(socket===ws)socket=null;};ws.onerror=()=>{};}catch(e){socket=null;}}
function acceptTraffic(data){
 const time=Date.now();if(S.traffic.length&&time-S.traffic.at(-1).time>12000){S.traffic=[];S.trafficStarted=time;}
 S.chartDuration=S.traffic.length?Math.max(200,Math.min(6000,time-S.traffic.at(-1).time)):1000;
 if(!S.traffic.length)S.trafficStarted=time;S.traffic.push({...data,time});S.trafficShifted=time-S.trafficStarted>=60000;
 while(S.traffic.length>2&&S.traffic[1].time<time-60000)S.traffic.shift();
 if($('rate-down'))$('rate-down').textContent='↓ '+bytes(data.down)+'/s';if($('rate-up'))$('rate-up').textContent='↑ '+bytes(data.up)+'/s';chartFromMax=chartMax;const peak=Math.max(1024,...S.traffic.flatMap(p=>[p.down,p.up]));chartToMax=2**Math.ceil(Math.log2(peak*1.15));chartStart=performance.now();cancelAnimationFrame(chartFrame);animateTraffic();
}
function animateTraffic(){const progress=Math.min(1,(performance.now()-chartStart)/(S.chartDuration||1000));drawTraffic(progress);if(progress<1&&S.view==='overview'&&!document.hidden)chartFrame=requestAnimationFrame(animateTraffic);}
function drawTraffic(progress=1){
 const canvas=$('traffic');if(!canvas)return;const w=canvas.clientWidth;if(!w)return;const h=160,scale=devicePixelRatio||1;
 if(canvas.width!==Math.round(w*scale)||canvas.height!==Math.round(h*scale)){canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);}
 const ctx=canvas.getContext('2d');ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,w,h);
 const eased=progress;chartMax=chartFromMax+(chartToMax-chartFromMax)*eased;
 const left=56,right=w-12,top=14,bottom=136;
 ctx.font='10px system-ui';ctx.textBaseline='middle';ctx.lineWidth=1;
 for(let i=0;i<=3;i++){const y=top+(bottom-top)*i/3;ctx.fillStyle='#81909a';ctx.textAlign='right';ctx.fillText(bytes(chartMax*(3-i)/3)+'/s',left-8,y);ctx.strokeStyle='#e6ecef';ctx.setLineDash([3,5]);ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(right,y);ctx.stroke();}
 ctx.setLineDash([]);ctx.fillStyle='#81909a';ctx.textAlign='left';ctx.fillText(S.trafficShifted?'60 秒前':'开始',left,151);ctx.textAlign='center';ctx.fillText(S.trafficShifted?'30 秒前':'30 秒',(left+right)/2,151);ctx.textAlign='right';ctx.fillText(S.trafficShifted?'现在':'60 秒',right,151);
 ctx.save();ctx.beginPath();ctx.rect(left,top-4,right-left,bottom-top+8);ctx.clip();
 function curve(points){ctx.moveTo(points[0].x,points[0].y);for(let i=1;i<points.length;i++){const previous=points[i-1],p=points[i],middle=(previous.x+p.x)/2;ctx.bezierCurveTo(middle,previous.y,middle,p.y,p.x,p.y);}}
 for(const [key,color]of [['down','#23986a'],['up','#2581ad']]){
  const newest=S.traffic.at(-1),previous=S.traffic.at(-2),displayTime=previous?previous.time+(newest.time-previous.time)*eased:newest?.time;
  const startTime=S.trafficShifted?displayTime-60000:S.trafficStarted;
  const points=S.traffic.map((p,i)=>{const last=i===S.traffic.length-1;let value=p[key];if(last&&i>0)value=S.traffic[i-1][key]+(value-S.traffic[i-1][key])*eased;const x=left+((last?displayTime:p.time)-startTime)/60000*(right-left);return{x,y:bottom-Math.min(value/chartMax,1)*(bottom-top)};});
  if(!points.length)continue;
  const fill=ctx.createLinearGradient(0,top,0,bottom);fill.addColorStop(0,color+'30');fill.addColorStop(1,color+'03');ctx.beginPath();curve(points);ctx.lineTo(points.at(-1).x,bottom);ctx.lineTo(points[0].x,bottom);ctx.closePath();ctx.fillStyle=fill;ctx.fill();
  ctx.beginPath();curve(points);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.lineJoin='round';ctx.lineCap='round';ctx.stroke();const last=points.at(-1);ctx.beginPath();ctx.arc(last.x,last.y,3,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();
 }ctx.restore();
}
for(const [view,[name,image]]of Object.entries(views)){const b=button(name,()=>navigate(view));b.prepend(icon(image));b.dataset.view=view;b.classList.toggle('active',view===S.view);document.querySelector('nav').append(b);}
window.addEventListener('hashchange',()=>{const view=location.hash.slice(1)||'overview';if(view!==S.view)navigate(view);});
$('refresh').addEventListener('click',()=>refresh().catch(error));$('cancel').addEventListener('click',()=>confirmDone(false));$('ok').addEventListener('click',()=>confirmDone(true));$('confirm').addEventListener('cancel',e=>{e.preventDefault();confirmDone(false);});document.addEventListener('visibilitychange',manageTraffic);window.addEventListener('resize',drawTraffic);
setInterval(async()=>{if(document.hidden||!S.running||!['overview','connections'].includes(S.view)||busy)return;try{await readConnections();if(S.view==='connections')drawConnections?.();else{manageTraffic();const metrics=document.querySelectorAll('.metric strong');if(metrics[1])metrics[1].textContent=S.connections.length;const totals=$('totals');if(totals){totals.children[0].textContent='累计下载 '+bytes(S.download);totals.children[1].textContent='累计上传 '+bytes(S.upload);}}}catch(e){error(e);}},5000);
refresh().catch(error);
